status = [

  # Buildkite: stack build
  "buildkite/cardano-chain",
  # Hydra: build for required jobset
  "ci/hydra:serokell:cardano-chain:required",
]
timeout_sec = 3600
required_approvals = 1
delete_merged_branches = true
block_labels = [ "DO NOT MERGE", "wip" ]
