status = [

  # Buildkite: stack build
  "buildkite/cardano-ledger",
  # Hydra: build for required jobset
  "ci/hydra:Cardano:cardano-ledger:required",
]
timeout_sec = 3600
required_approvals = 1
delete_merged_branches = true
block_labels = [ "DO NOT MERGE", "wip" ]
